//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charoentech_Web
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class BANNER
    {
        public int ID { get; set; }
        public string IMAGE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public HttpPostedFileBase ImageFile { get; set; } 
    }
}
