//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charoentech_Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CharoenTechEntities : DbContext
    {
        public CharoenTechEntities()
            : base("name=CharoenTechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ITEM> ITEM { get; set; }
        public virtual DbSet<ITEM_CATE> ITEM_CATE { get; set; }
        public virtual DbSet<SERVICE_CATE> SERVICE_CATE { get; set; }
        public virtual DbSet<BLOG> BLOG { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<TEXT> TEXT { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<BANNER> BANNER { get; set; }
        public virtual DbSet<DOWNLOAD> DOWNLOAD { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
    }
}
