//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charoentech_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_CATE
    {
        public int ITEM_CATE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int STATUS { get; set; }
        public Nullable<int> FLAG_HOME_PG { get; set; }
        public string IMAGE { get; set; }
    }
}
