//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charoentech_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int ITEM_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<int> FLAG { get; set; }
        public Nullable<int> ORDER_LIST { get; set; }
        public string IMAGE { get; set; }
        public string BOSURE { get; set; }
        public string PO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public byte[] CREATED_DT { get; set; }
        public Nullable<int> INDEX_HOME_PG { get; set; }
        public Nullable<int> ITEM_CATE_ID { get; set; }
        public Nullable<int> BEST_SALLER { get; set; }
        public Nullable<int> NEW { get; set; }
        public string DOWNLOAD_TAB { get; set; }
    }
}
