//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charoentech_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_CATE
    {
        public int SERVICE_CATE_ID { get; set; }
        public string NAME { get; set; }
        public string TOPIC { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGE { get; set; }
        public string ICON { get; set; }
        public Nullable<int> ORDER_LIST { get; set; }
        public int STATUS { get; set; }
        public byte[] CREATED_DT { get; set; }
    }
}
