//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charoentech_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXT
    {
        public int TEXT_ID { get; set; }
        public string TASK { get; set; }
        public string ICON { get; set; }
        public string NAME { get; set; }
        public string TOPIC { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGE { get; set; }
        public int STATUS { get; set; }
    }
}
